---
title: "Multilevel models"
output: html_notebook
---

This notebook deals with multi-level models from Chapter 4. These will probably be the most heavily used types of model structure in future work on INLA.

```{r}
library(INLA)
library("faraway")
data(penicillin)
summary(penicillin)

## Random intercept model

# Set prior on precision
prec.prior <- list(prec = list(param = c(0.001, 0.001)))

# Reset reference level
penicillin$treat <- relevel(penicillin$treat, "D")

inla.pen <- inla(yield ~ 1 + treat + f(blend, model = "iid",
    hyper = prec.prior),
  data = penicillin, control.predictor = list(compute = TRUE))

# Comparison
library("lme4")
lmer.pen <- lmer(yield ~ 1 + treat + (1|blend), data = penicillin)

summary(lmer.pen)
summary(inla.pen)

# Alternatively this model can also be fitted by manually specifying the random effects
# Using a model matrix
Z <- as(model.matrix(~ 0 + blend, data = penicillin), "Matrix")
# Create index
penicillin$ID <- 1:nrow(penicillin)
# Refit
inla.pen.z <- inla(yield ~ 1 + treat +  f(ID, model = "z", Z = Z,
  hyper = list(prec = list(param = c(0.001, 0.001)))),
  data = penicillin, control.predictor = list(compute = TRUE))
summary(inla.pen.z)

```

## Multilevel models with nested effects

```{r}
data(eggs)

Zlt <- as(model.matrix( ~ 0 + Lab:Technician, data = eggs), "Matrix")
Zlts <- as(model.matrix( ~ 0 + Lab:Technician:Sample, data = eggs), "Matrix")

# Index for techinician
eggs$IDt <- 1:nrow(eggs)
# Index for technician:sample
eggs$IDts <- 1:nrow(eggs)

inla.eggs <- inla(Fat ~ 1 + f(Lab, model = "iid", hyper = prec.prior) +
    f(IDt, model = "z", Z = Zlt, hyper = prec.prior) +
    f(IDts, model = "z", Z = Zlts, hyper = prec.prior),
  data = eggs, control.predictor = list(compute = TRUE))

summary(inla.eggs)

# Alternative
# Create index for iid
eggs$labtech <- as.factor(apply(Zlt, 1, function(x){names(x)[x == 1]}))
eggs$labtechsamp <- as.factor(apply(Zlts, 1, function(x){names(x)[x == 1]}))

inla.eggs.iid <- inla(Fat ~ 1 + f(Lab, model = "iid", hyper = prec.prior) +
    f(labtech, model = "iid", hyper = prec.prior) +
    f(labtechsamp, model = "iid", hyper = prec.prior),
  data = eggs, control.predictor = list(compute = TRUE))

summary(inla.eggs.iid)

```

##  Multilevel models with complex structure

```{r}
# Get the testing data
download.file('https://www.jstatsoft.org/index.php/jss/article/downloadSuppFile/v045i05/class_size_data.txt',destfile = 'class_size_data.txt')

# Read data
csize_data <- read.csv (file = "class_size_data.txt", header = FALSE,
  sep = "", dec = ".")

#Set names
names(csize_data) <- c("clsnr", "pupil", "nlitpre", "nmatpre", "nlitpost",
  "nmatpost", "csize")

#Set NA's
csize_data [csize_data < -1e+29 ] <- NA

#Set class size levels
csize_data$csize <- as.factor(csize_data$csize)
levels(csize_data$csize) <- c("<=19", "20-24", "25-29", ">=30")

summary(csize_data)

# Ignore missing data
csize_data2 <- na.omit(csize_data[, -5])

# Fit hierachical model
inla.csize <- inla(nmatpost ~ 1 + nmatpre + nlitpre + csize +
  f(clsnr, model = "iid"), data = csize_data2)

summary(inla.csize)
```

## Multilevel models for longitudinal data

```{r}
library("lme4")
data(sleepstudy)

sleepstudy$Reaction <- sleepstudy$Reaction / 1000

inla.sleep <- inla(Reaction ~ 1 + Days + f(Subject, model = "iid"),
  data = sleepstudy)

summary(inla.sleep)

# Now fit a model with subject level random slopes
inla.sleep.w <- inla(Reaction ~ 1 + f(Subject, Days, model = "iid"),
  data = sleepstudy, control.predictor = list(compute = TRUE))
# First arguement defines the group (number of slopes) and second the random slope, e.g. covariate that varies per subject
summary(inla.sleep.w)


```

## Multilevel models for binary data

```{r}
# Data from Gelman & Hill
election88 <- read.table(file = "polls.subset.dat")

# Formatting
election88$age <- as.factor(election88$age)
levels(election88$age) <- c("18-29", "30-44", "45-64", "65+")

election88$edu <- as.factor(election88$edu)
levels(election88$edu) <- c("not.high.school.grad", "high.school.grad",
  "some.college", "college.grad")

# Add region
election88$region <- c(3, 4, 4, 3, 4, 4, 1, 1, 5, 3, 3, 4, 4, 2, 2, 2, 2,
  3, 3, 1, 1, 1, 2, 2, 3, 2, 4, 2, 4, 1, 1, 4, 1, 3, 2, 2, 3, 4, 1, 1, 3,
  2, 3, 3, 4, 1, 3, 4, 1, 2, 4)[as.numeric(election88$state)]


inla.elec88 <- inla(bush ~ 1 + female + black + age + edu +
    f(state, model = "iid"),
  data = election88, family = "binomial",
  control.predictor = list(link = 1)) # For setting a logit link function

summary(inla.elec88)


```

## Multilevel models for count data

```{r}
nyc.stops <- read.table(file = "frisk_with_noise.dat", skip = 6, 
  header = TRUE)

# Add labels to factors
nyc.stops$eth <- as.factor(nyc.stops$eth)
levels(nyc.stops$eth) <- c("black", "hispanic", "white")
nyc.stops$eth <- relevel(nyc.stops$eth, "white")

nyc.stops$crime <- as.factor(nyc.stops$crime)
levels(nyc.stops$crime) <- c("violent", "weapons", "property", "drug")

# Aggregate by precinct
nyc.stops.agg <- aggregate(cbind(stops, past.arrests, pop) ~ precinct + eth,
  data = nyc.stops, sum)

# Population is summed 4 times
nyc.stops.agg$pop <- nyc.stops.agg$pop / 4

# Include offset as counts were derived over 15 months period
nyc.inla <- inla(stops ~ eth + f(precinct, model = "iid"),
  data = nyc.stops.agg, offset = log((15 / 12) * past.arrests),
  family = "poisson")

summary(nyc.inla)

# Ethnicity precinct index
nyc.stops.agg$ID <- 1:nrow(nyc.stops.agg)
nyc.inla2 <- inla(stops ~ eth + f(precinct, model = "iid") + 
    f(ID, model = "iid"), 
  data = nyc.stops.agg, offset = log((15/12) * past.arrests),
  family = "poisson")

summary(nyc.inla2)

# Random effect estimates that could be plotted
# Add r. eff. estimates
nyc.inla$summary.random$precinct$mean

```

