---
title: "Chapter 10 - Counting and classification"
output: html_notebook
---

```{r}
library(rethinking)
data(chimpanzees)
d <- chimpanzees

# And a model with just the intercept
m10.1 <- map(
      alist(
        pulled_left ~ dbinom( 1 , p ) ,
        logit(p) <- a ,
        a ~ dnorm(0,10)
      ) ,
  data = d )
precis(m10.1) # Convert back with logistic 
logistic(0.32) # 58 % probability prefer the left-hand lever (without any controlling variables)

# One model with a single predictor
m10.2 <- map(
      alist(
        pulled_left ~ dbinom( 1 , p ) ,
        logit(p) <- a + bp*prosoc_left ,
        a ~ dnorm(0,10) , # norm for intercept
        bp ~ dnorm(0,10) # norm for beta
      ) ,
  data=d )

# One interaction model with weakly informative priors
m10.3 <- map(
    alist(
      pulled_left ~ dbinom( 1 , p ) ,
      logit(p) <- a + (bp + bpC*condition)*prosoc_left ,
      a ~ dnorm(0,10) ,
      bp ~ dnorm(0,10) ,
      bpC ~ dnorm(0,10) # Interaction
  ) ,
  data=d )

compare(m10.1,m10.2,m10.3)
# Interaction model is poorer than m10.2
# Why?
precis(m10.3) # relative improvement high, but absolute is not

# Build an ensemble model
# dummy data for predictions across treatments 
d.pred <- data.frame(
    prosoc_left = c(0,1,0,1), # right/left/right/left
    condition = c(0,0,1,1) # control/control/partner/partner
  )
# build prediction ensemble
chimp.ensemble <- ensemble( m10.1 , m10.2 , m10.3 , data=d.pred )

# summarize
pred.p <- apply( chimp.ensemble$link , 2 , mean )
pred.p.PI <- apply( chimp.ensemble$link , 2 , PI )

# empty plot frame with good axes 10.11
plot( 0 , 0 , type="n" , xlab="prosoc_left/condition" ,ylab="proportion pulled left" , ylim=c(0,1) , xaxt="n" ,xlim=c(1,4) )
axis( 1 , at=1:4 , labels=c("0/0","1/0","0/1","1/1") )
# plot raw data, one trend for each of 7 individual chimpanzees
# will use by() here; see Overthinking box for explanation
p <- by( d$pulled_left ,list(d$prosoc_left,d$condition,d$actor) , mean )

for ( chimp in 1:7 ) lines( 1:4 , as.vector(p[,,chimp]) , col=rangi2 , lwd=1.5 )
# now superimpose posterior predictions
lines( 1:4 , pred.p )
shade( pred.p.PI , 1:4 )

# For stan equivalent model
d2 <- d
d2$recipient <- NULL
# re-use map fit to get the formula
m10.3stan <- map2stan( m10.3 , data=d2 , iter=1e4 , warmup=1000 )
precis(m10.3stan)
```

Now lets fit a new model that specifies a different incept for each chimp actor

```{r}

m10.4 <- map2stan( 
    alist(
      pulled_left ~ dbinom( 1 , p ) ,
      logit(p) <- a[actor] + (bp + bpC*condition)*prosoc_left ,
      a[actor] ~ dnorm(0,10), # Actor specific intercept
      bp ~ dnorm(0,10),
      bpC ~ dnorm(0,10)
    ) ,
  data=d2 , chains=2 , iter=2500 , warmup=500 )

precis( m10.4 , depth=2 ) # For each of them

```


Aggregated binomial examples

```{r}
library(rethinking)
data(UCBadmit)
d <- UCBadmit

# Are males more likely to be admitted?
d$male <- ifelse( d$applicant.gender=="male" , 1 , 0 ) 

m10.6 <- map(
  alist(
    admit ~ dbinom( applications , p ) ,
    logit(p) <- a + bm*male ,
    a ~ dnorm(0,10) ,
    bm ~ dnorm(0,10)
  ),
  data=d )
# Without male dummy variable
m10.7 <- map(
  alist(
    admit ~ dbinom( applications , p ) ,
    logit(p) <- a ,
    a ~ dnorm(0,10)
  ) ,
data=d )

compare( m10.6 , m10.7 )

# Absolute propabilty of being admitted
post <- extract.samples( m10.6 ) 
p.admit.male <- logistic( post$a + post$bm )
p.admit.female <- logistic( post$a )
diff.admit <- p.admit.male - p.admit.female
quantile( diff.admit , c(0.025,0.5,0.975) )
# Males are 14.2% more likely to be admitted


## Relative to females: How likely are males admitted?

# make index 
d$dept_id <- coerce_index( d$dept )

# Vary intercept by department
m10.8 <- map(
  alist(
    admit ~ dbinom( applications , p ) ,
    logit(p) <- a[dept_id] ,
    a[dept_id] ~ dnorm(0,10)
  ) , data=d )

# model with male difference as well
m10.9 <- map(
  alist(
    admit ~ dbinom( applications , p ) ,
    logit(p) <- a[dept_id] + bm*male ,
    a[dept_id] ~ dnorm(0,10) ,
    bm ~ dnorm(0,10)
  ), data=d )

# Compare all four
compare( m10.6 , m10.7 , m10.8 , m10.9 )
```

## Poisson 
Using the oceanin evolution data
```{r}
library(rethinking)
data(Kline)
d <- Kline

# Look for positive association between total tools and population and high contact

d$log_pop <- log(d$population)
d$contact_high <- ifelse( d$contact=="high" , 1 , 0 )

m10.10 <- map( 
               alist(
                   total_tools ~ dpois( lambda ), # Poisson distribution with shape <- likelyhood
                   log(lambda) <- a + bp*log_pop + # log link of shape by intercept + interaction
                       bc*contact_high + bpc*contact_high*log_pop,
                   a ~ dnorm(0,100),
                   c(bp,bc,bpc) ~ dnorm(0,1)
               ),
               data=d )
plot( precis(m10.10) )

# Does contact rate have an influence ?
post <- extract.samples(m10.10) # sample posterior
lambda_high <- exp( post$a + post$bc + (post$bp + post$bpc)*8 )
lambda_low <- exp( post$a + post$bp*8 )

# Posterior is distribution als well as the lamdas
diff <- lambda_high - lambda_low
sum(diff > 0)/length(diff)
# 95.5 % higher plausability that high contact islands have more tools

## Alternative models
# no interaction 
m10.11 <- map(
  alist(
  total_tools ~ dpois( lambda ),
  log(lambda) <- a + bp*log_pop + bc*contact_high,
  a ~ dnorm(0,100),
  c(bp,bc) ~ dnorm( 0 , 1 )
), data=d )

# no contact rate 
m10.12 <- map(
  alist(
  total_tools ~ dpois( lambda ),
  log(lambda) <- a + bp*log_pop,
  a ~ dnorm(0,100),
  bp ~ dnorm( 0 , 1 )
), data=d )

# no log-population
m10.13 <- map(
  alist(
  total_tools ~ dpois( lambda ),
  log(lambda) <- a + bc*contact_high,
  a ~ dnorm(0,100),
  bc ~ dnorm( 0 , 1 )
  ), data=d )

# intercept only "null model"
m10.14 <- map(
  alist(
  total_tools ~ dpois( lambda ),
  log(lambda) <- a,
  a ~ dnorm(0,100)
), data=d )

# compare all using WAIC
# adding n=1e4 for more stable WAIC estimates
# will also plot the comparison
( islands.compare <- compare(m10.10,m10.11,m10.12,m10.13,m10.14,n=1e4) )
plot(islands.compare)

# Finally calculate and plot an ensemble of best models

# make plot of raw data to begin
# point character (pch) indicates contact rate
pch <- ifelse( d$contact_high==1 , 16 , 1 )

# sequence of log-population sizes to compute over
log_pop.seq <- seq( from=6 , to=13 , length.out=30 )

# compute trend for high contact islands
d.pred <- data.frame(
  log_pop = log_pop.seq,
  contact_high = 1
)
lambda.pred.h <- ensemble( m10.10 , m10.11 , m10.12 , data=d.pred )
lambda.med <- apply( lambda.pred.h$link , 2 , median )
lambda.PI <- apply( lambda.pred.h$link , 2 , PI )


# plot predicted trend for high contact islands
plot( d$log_pop , d$total_tools , col=rangi2 , pch=pch ,
xlab="log-population" , ylab="total tools" )
lines( log_pop.seq , lambda.med , col=rangi2 )
shade( lambda.PI , log_pop.seq , col=col.alpha(rangi2,0.2) )

# And for low contact islands
# compute trend for low contact islands
d.pred <- data.frame(
    log_pop = log_pop.seq,
    contact_high = 0
  )
lambda.pred.l <- ensemble( m10.10 , m10.11 , m10.12 , data=d.pred )
lambda.med <- apply( lambda.pred.l$link , 2 , median )
lambda.PI <- apply( lambda.pred.l$link , 2 , PI )
# plot again
lines( log_pop.seq , lambda.med , lty=2 )
shade( lambda.PI , log_pop.seq , col=col.alpha("black",0.1) )

```

The influence of centering on model fit and inference

```{r}

# construct centered predictor
d$log_pop_c <- d$log_pop - mean(d$log_pop)

# re-estimate
m10.10stan.c <- map2stan(
  alist(
    total_tools ~ dpois( lambda ) ,
    log(lambda) <- a + bp*log_pop_c + bc*contact_high +
    bcp*log_pop_c*contact_high ,
    a ~ dnorm(0,10) ,
    bp ~ dnorm(0,1) ,
    bc ~ dnorm(0,1) ,
    bcp ~ dnorm(0,1)
  ) ,
data=d , iter=3000 , warmup=1000 , chains=4 )

plot( precis(m10.10stan.c) )

```

<hr>